logging:
  file: ${log.path:../logs}/${metadata.category}.log
  level:
    org.springframework: debug
    com.ezcoding: debug
server:
  port: 80
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${metadata.category}
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    druid:
      url: jdbc:mysql://cdb-m7a0slf1.gz.tencentcdb.com:10079/account?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: account
      password: "CRO3NJUGSWTXbk0r"
      driver-class-name: com.mysql.cj.jdbc.Driver
      maxActive: 20
      initialSize: 0
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 1800000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      maxOpenPreparedStatements: 10
      removeAbandonedTimeout: 1800
      logAbandoned: true
      filters: stat,wall,slf4j
  redis:
    host: 134.175.139.134
    port: 6379
    password: "9(%4_Er8#MiP7$"
    jedis:
      pool:
        max-idle: 8
        max-active: 8
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka:80/eureka/
  instance:
    #10秒发送一次心跳包
    lease-renewal-interval-in-seconds: 10
    #30秒没有发送心跳，本节点已经宕机
    lease-expiration-duration-in-seconds: 30
feign:
  client:
    config:
      default:
        connectTimeout: 0
        readTimeout: 0
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${ribbon.ReadTimeout}
#Token
token:
  header: Authorization
  expiration: 604800
  subject: token
  issuer: ezcoding
#腾讯云存储Cos
cos:
  accessKey: AKIDKQHuIQP2XpseYEnpjOnxt2yaw6aqhgOs
  secretKey: OYYKtDIfojPp9D7nDOl63kFVVFo8EQQA
  regionName: ap-guangzhou
  threadPoolNum: 10
headerCosSettings:
  bucketName: escp-1257324706
  basePath: header/
#腾讯云SMS
sms:
  appId: 1400182944
  appKey: 1091c3e37ba41c3a666a6b0a650d0a38
  smsSign: escp
  registerTemplateId: 276497
metadata:
  dataCenterNo: 0
  category: account
  categoryNo: 0
zookeeper:
  auth: ezcoding:Cw7z6HV8Dm5JuKN3
  ips:
    - 134.175.139.134:2181